import { WorkoutActivityType } from "@kingstinct/react-native-healthkit";

export const WORKOUT_ACTIVITY_TYPE_LABELS = {
	[WorkoutActivityType.americanFootball]: "American Football",
	[WorkoutActivityType.archery]: "Archery",
	[WorkoutActivityType.australianFootball]: "Australian Football",
	[WorkoutActivityType.badminton]: "Badminton",
	[WorkoutActivityType.baseball]: "Baseball",
	[WorkoutActivityType.basketball]: "Basketball",
	[WorkoutActivityType.bowling]: "Bowling",
	[WorkoutActivityType.boxing]: "Boxing",
	[WorkoutActivityType.climbing]: "Climbing",
	[WorkoutActivityType.cricket]: "Cricket",
	[WorkoutActivityType.crossTraining]: "Cross Training",
	[WorkoutActivityType.curling]: "Curling",
	[WorkoutActivityType.cycling]: "Cycling",
	[WorkoutActivityType.dance]: "Dance",
	[WorkoutActivityType.danceInspiredTraining]: "Dance Inspired Training",
	[WorkoutActivityType.elliptical]: "Elliptical",
	[WorkoutActivityType.equestrianSports]: "Equestrian Sports",
	[WorkoutActivityType.fencing]: "Fencing",
	[WorkoutActivityType.fishing]: "Fishing",
	[WorkoutActivityType.functionalStrengthTraining]:
		"Functional Strength Training",
	[WorkoutActivityType.golf]: "Golf",
	[WorkoutActivityType.gymnastics]: "Gymnastics",
	[WorkoutActivityType.handball]: "Handball",
	[WorkoutActivityType.hiking]: "Hiking",
	[WorkoutActivityType.hockey]: "Hockey",
	[WorkoutActivityType.hunting]: "Hunting",
	[WorkoutActivityType.lacrosse]: "Lacrosse",
	[WorkoutActivityType.martialArts]: "Martial Arts",
	[WorkoutActivityType.mindAndBody]: "Mind and Body",
	[WorkoutActivityType.mixedMetabolicCardioTraining]:
		"Mixed Metabolic Cardio Training",
	[WorkoutActivityType.paddleSports]: "Paddle Sports",
	[WorkoutActivityType.play]: "Play",
	[WorkoutActivityType.preparationAndRecovery]: "Preparation and Recovery",
	[WorkoutActivityType.racquetball]: "Racquetball",
	[WorkoutActivityType.rowing]: "Rowing",
	[WorkoutActivityType.rugby]: "Rugby",
	[WorkoutActivityType.running]: "Running",
	[WorkoutActivityType.sailing]: "Sailing",
	[WorkoutActivityType.skatingSports]: "Skating Sports",
	[WorkoutActivityType.snowSports]: "Snow Sports",
	[WorkoutActivityType.soccer]: "Soccer",
	[WorkoutActivityType.softball]: "Softball",
	[WorkoutActivityType.squash]: "Squash",
	[WorkoutActivityType.stairClimbing]: "Stair Climbing",
	[WorkoutActivityType.surfingSports]: "Surfing Sports",
	[WorkoutActivityType.swimming]: "Swimming",
	[WorkoutActivityType.tableTennis]: "Table Tennis",
	[WorkoutActivityType.tennis]: "Tennis",
	[WorkoutActivityType.trackAndField]: "Track and Field",
	[WorkoutActivityType.traditionalStrengthTraining]:
		"Traditional Strength Training",
	[WorkoutActivityType.volleyball]: "Volleyball",
	[WorkoutActivityType.walking]: "Walking",
	[WorkoutActivityType.waterFitness]: "Water Fitness",
	[WorkoutActivityType.waterPolo]: "Water Polo",
	[WorkoutActivityType.waterSports]: "Water Sports",
	[WorkoutActivityType.wrestling]: "Wrestling",
	[WorkoutActivityType.yoga]: "Yoga",
	[WorkoutActivityType.barre]: "Barre",
	[WorkoutActivityType.coreTraining]: "Core Training",
	[WorkoutActivityType.crossCountrySkiing]: "Cross Country Skiing",
	[WorkoutActivityType.downhillSkiing]: "Downhill Skiing",
	[WorkoutActivityType.flexibility]: "Flexibility",
	[WorkoutActivityType.highIntensityIntervalTraining]:
		"High Intensity Interval Training",
	[WorkoutActivityType.jumpRope]: "Jump Rope",
	[WorkoutActivityType.kickboxing]: "Kickboxing",
	[WorkoutActivityType.pilates]: "Pilates",
	[WorkoutActivityType.snowboarding]: "Snowboarding",
	[WorkoutActivityType.stairs]: "Stairs",
	[WorkoutActivityType.stepTraining]: "Step Training",
	[WorkoutActivityType.wheelchairWalkPace]: "Wheelchair Walk Pace",
	[WorkoutActivityType.wheelchairRunPace]: "Wheelchair Run Pace",
	[WorkoutActivityType.taiChi]: "Tai Chi",
	[WorkoutActivityType.mixedCardio]: "Mixed Cardio",
	[WorkoutActivityType.handCycling]: "Hand Cycling",
	[WorkoutActivityType.discSports]: "Disc Sports",
	[WorkoutActivityType.fitnessGaming]: "Fitness Gaming",
	[WorkoutActivityType.cardioDance]: "Cardio Dance",
	[WorkoutActivityType.socialDance]: "Social Dance",
	[WorkoutActivityType.pickleball]: "Pickleball",
	[WorkoutActivityType.cooldown]: "Cooldown",
	[WorkoutActivityType.swimBikeRun]: "Swim Bike Run",
	[WorkoutActivityType.transition]: "Transition",
	[WorkoutActivityType.underwaterDiving]: "Underwater Diving",
	[WorkoutActivityType.other]: "Other",
} satisfies Record<WorkoutActivityType, string>;

export function getWorkoutActivityTypeLabel(type: WorkoutActivityType): string {
	return WORKOUT_ACTIVITY_TYPE_LABELS[type] ?? "Workout";
}
